Exception on /messages/ [POST]
Traceback (most recent call last):
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 21, in reply_message_for_memory
    max_index = len(content['response']['events'])
KeyError: 'events'
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 40, in reply_message_for_memory
    event = content['response']['events'][select_idx]
IndexError: list index out of range
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 44, in reply_message_for_memory
    event = content['response']['events']['event_'+str(select_idx)]
TypeError: list indices must be integers or slices, not str
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 44, in reply_message_for_memory
    event = content['response']['events'][select_idx]
IndexError: list index out of range
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 45, in reply_message_for_memory
    messages = convert_memory_message(event, type)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\controllers\tone.py", line 137, in convert_memory_message
    schedule = event['schedule_where'] + "에서 " + event['schedule_what'] + "했었구나!"
KeyError: 'schedule_where'
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 21, in reply_message_for_memory
    max_index = len(content['response']['events'])
KeyError: 'events'
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Devuri\workspace\server\djbot-venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 49, in reply_message_for_memory
    messages = convert_memory_message(event[0], type)
  File "E:\Devuri\workspace\server\DajeongBot-server\djbot\controllers\tone.py", line 137, in convert_memory_message
    schedule = event['schedule_where'] + "에서 " + event['schedule_what'] + "했었구나!"
TypeError: 'Event' object is not subscriptable
