Exception on /messages/ [POST]
Traceback (most recent call last):
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 60, in reply_message_for_memory
    "events": content['response']['events']
KeyError: 'events'
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 60, in reply_message_for_memory
    "events": content['response']['events']
KeyError: 'events'
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 50, in reply_message_for_memory
    print(content['response']['events'])
KeyError: 'events'
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 23, in reply_message_for_memory
    if content['response']['select_idx'] == -1:
KeyError: 'select_idx'
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 23, in reply_message_for_memory
    if content['response']['select_idx'] == -1:
KeyError: 'select_idx'
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 24, in reply_message_for_memory
    if content['response']['select_idx'] == -1:
KeyError: 'select_idx'
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 36, in add_messages
    result = reply_message_for_memory(content)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\controllers\memory.py", line 24, in reply_message_for_memory
    if content['response']['select_idx'] == -1:
KeyError: 'select_idx'
